DELIMITER //
create trigger trigger_171111023_171111008 after 
	update on DETAIL_PEMBELIAN  
		FOR EACH ROW 
		BEGIN 

IF old.JUMLAH_BARANG - new.JUMLAH_BARANG <=-1 THEN BEGIN 
update BARANG set STOK = STOK + (old.JUMLAH_BARANG - new.JUMLAH_BARANG)
where BARANG.ID_BARANG4 = new.ID_BARANG4;
END; END IF;

IF old.JUMLAH_BARANG - new.JUMLAH_BARANG >=1 THEN BEGIN 
update BARANG set STOK = STOK + (old.JUMLAH_BARANG - new.JUMLAH_BARANG )
where BARANG.ID_BARANG4 = new.ID_BARANG4;
END; END IF;

END
//
DELIMITER ;
